parameters: {}

steps:
  - task: AzureCLI@2
    displayName: "Create + Stream Azure ML Job, then Register Baseline"
    inputs:
      azureSubscription: mlops_anomaly_detection
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        $jobName = az ml job create `
          --file "./jobs/training-job.yml" `
          --resource-group $(RESOURCE_GROUP) `
          --workspace-name $(WORKSPACE) `
          --query name -o tsv

        Write-Host "Training job name: $jobName"

        az ml job stream `
          --name $jobName `
          --resource-group $(RESOURCE_GROUP) `
          --workspace-name $(WORKSPACE)

        New-Item -ItemType Directory -Force -Path baseline_out | Out-Null

        az ml job download `
          --name $jobName `
          --resource-group $(RESOURCE_GROUP) `
          --workspace-name $(WORKSPACE) `
          --output-name baseline_reference `
          --download-path baseline_out

        az ml data create `
          --name padim_drift_baseline `
          --version $jobName `
          --type uri_file `
          --path baseline_out/baseline_reference `
          --resource-group $(RESOURCE_GROUP) `
          --workspace-name $(WORKSPACE)
