from azure.ai.ml import MLClient
from azure.ai.ml.entities import Data
from azure.ai.ml.constants import AssetTypes
from azure.identity import DefaultAzureCredential
import os

SUB = os.environ["SUBSCRIPTION_ID"]
RG  = os.environ["RESOURCE_GROUP"]
WS  = os.environ["WORKSPACE"]

BASELINE_PATH = os.environ.get("BASELINE_PATH", "outputs/baseline_reference.csv")
BASELINE_NAME = os.environ.get("BASELINE_DATA_ASSET_NAME", "padim_drift_baseline")
BASELINE_VER  = os.environ.get("BASELINE_DATA_ASSET_VERSION", "1")

ml_client = MLClient(DefaultAzureCredential(), SUB, RG, WS)

data = Data(
    name=BASELINE_NAME,
    version=BASELINE_VER,
    type=AssetTypes.URI_FILE,
    path=BASELINE_PATH,
    description="Baseline drift features generated by extract_drift_features"
)
ml_client.data.create_or_update(data)
print(f"Registered baseline data asset: {BASELINE_NAME}:{BASELINE_VER}")
